[package]
name = "soundboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.17.3"
color-eyre = "0.6.3"
ratatui = "0.26.2"
crossterm = "0.27.0"
taffy = "0.4.3"